### ISSUE TITLE
Invalid version prevents installation to succeed with pyhton 3.11

### ISSUE THREAD

**Issue by antolinos** [icatproject/python-icat#114]
Dear @RKrahl ,

I am having some issues with  CI pipelines that use the latest alpine version are failing to install python-icat.
It seems that alpine comes with 3.11 throwing the following exception:
```
> [7/8] RUN git clone https://github.com/icatproject/python-icat.git && cd python-icat && python3 setup.py build && python3 setup.py install:
#12 2.097   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 305, in get_finalized_command
#12 2.097     cmd_obj.ensure_finalized()
#12 2.097   File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
#12 2.097     self.finalize_options()
#12 2.097   File "/usr/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 219, in finalize_options
#12 2.097     parsed_version = packaging.version.Version(self.egg_version)
#12 2.098                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 2.098   File "/usr/lib/python3.11/site-packages/setuptools/_vendor/packaging/version.py", line 197, in __init__
#12 2.098     raise InvalidVersion(f"Invalid version: '{version}'")
#12 2.098 setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'UNKNOWN'
```

I realized that there was a warning with 3.9:
```
#12 [7/8] RUN git clone https://github.com/icatproject/python-icat.git && cd python-icat && python3 setup.py build && python3 setup.py install
#12 0.392 Cloning into 'python-icat'...
#10 4.165 warning: cannot determine version number
#10 4.179 /usr/lib/python3.9/site-packages/setuptools/dist.py:475: UserWarning: The version specified ('UNKNOWN') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
#10 4.179   warnings.warn(
#10 4.181 running build
#10 4.181 running build_py
#10 4.181 running meta
#10 4.182 creating build
#10 4.183 creating build/lib
#10 4.183 creating build/lib/icat
#10 4.183 copying icat/__init__.py -> build/lib/icat
#10 4.183 copying icat/exception.py -> build/lib/icat
#10 4.183 copying icat/dumpfile.py -> build/lib/icat
#10 4.184 copying icat/eval.py -> build/lib/icat
#10 4.184 copying icat/chunkedhttp.py -> build/lib/icat
#10 4.184 copying icat/client.py -> build/lib/icat
#10 4.185 copying icat/query.py -> build/lib/icat
#10 4.185 copying icat/dump_queries.py -> build/lib/icat
#10 4.185 copying icat/helper.py -> build/lib/icat
#10 4.186 copying icat/listproxy.py -> build/lib/icat
#10 4.186 copying icat/sslcontext.py -> build/lib/icat
#10 4.186 copying icat/config.py -> build/lib/icat
#10 4.186 copying icat/entities.py -> build/lib/icat
#10 4.187 copying icat/entity.py -> build/lib/icat
#10 4.187 copying icat/dumpfile_yaml.py -> build/lib/icat
#10 4.188 copying icat/dumpfile_xml.py -> build/lib/icat
#10 4.188 copying icat/ids.py -> build/lib/icat
#10 4.188 copying icat/authinfo.py -> build/lib/icat
#10 4.189 running build_scripts
#10 4.190 creating build/scripts-3.9
#10 4.191 copying and adjusting icatdump.py -> build/scripts-3.9
#10 4.191 copying and adjusting icatingest.py -> build/scripts-3.9
#10 4.191 copying and adjusting wipeicat.py -> build/scripts-3.9
#10 4.191 changing mode of build/scripts-3.9/icatdump.py from 644 to 755
#10 4.191 changing mode of build/scripts-3.9/icatingest.py from 644 to 755
#10 4.191 changing mode of build/scripts-3.9/wipeicat.py from 644 to 755
#10 4.447 /usr/lib/python3.9/site-packages/setuptools/dist.py:475: UserWarning: The version specified ('UNKNOWN') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
```

I was wondering, what do you recommend to do?

Thanks!
Alex

**Comment by RKrahl** [comment]
> ```
> > [7/8] RUN git clone https://github.com/icatproject/python-icat.git && cd python-icat && python3 setup.py build && python3 setup.py install:
> ```

This is not the way python-icat is supposed to be installed.  Please use the distribution package from PyPI of the latest stable release instead.  E.g.
```
$ pip install python-icat
```
See the [install instructions](https://python-icat.readthedocs.io/en/stable/install.html) for details.

**Comment by antolinos** [comment]
Hi Rolf,

In the section `Installation from the source distribution` of the documentation says that it can be install in such a way no?
https://python-icat.readthedocs.io/en/stable/install.html
![image](https://github.com/icatproject/python-icat/assets/2901169/5c39fb90-e6bc-41c3-8cde-1165e07e267c)

In any case, I will install with pip as you are suggesting.

**Comment by RKrahl** [comment]
That section is titled “Installation from the source distribution”. A distribution is a form to package the software in order to publish a release. You can download the python-icat 1.0.0 source distribution either from https://files.pythonhosted.org/packages/18/ec/f3d4a67297568ef616590f1b77e41b6eb57c17ba6b3e762adee2ecb7b4f8/python-icat-1.0.0.tar.gz or from https://github.com/icatproject/python-icat/releases/download/1.0.0/python-icat-1.0.0.tar.gz. If you start from a source distribution, the instructions in this section work.

The development source tree as cloned from the git repo is not a source distribution. And the very next section in the install instructions, titled “Building from development sources” explain why the same procedure will not work starting from development sources and would you would need to do in that case instead.

**Comment by antolinos** [comment]
For the records, it works like a charm with pip install as recommend. Thanks!
