### ISSUE TITLE
Ensure compatibility with ICAT 4.6

### ISSUE THREAD

**Issue by RKrahl** [icatproject/python-icat#12]
Make sure python-icat is compatible with the upcoming ICAT version 4.6.

Issues identified so far:
- [x] New exception `NOT_IMPLEMENTED`.

Need to wait for the release of ICAT 4.6 for the final list.

**Comment by fisherab** [comment]
The lucene calls are very likely to change a bit when Wayne has tried to use them - otherwise no further changes are planned.
