### ISSUE TITLE
Can't create a client against icat.server 6.1.0-SNAPSHOT: `icat.exception.ICATParameterError: Parameter is not an ICAT entity`

### ISSUE THREAD

**Issue by louise-davies** [icatproject/python-icat#153]
Hello,

The new icat.server snapshot ([6.1.0-SNAPSHOT](https://repo.icatproject.org/repo/org/icatproject/icat.server/6.1.0-SNAPSHOT/icat.server-6.1.0-20240408.104443-6-distro.zip)) no longer works with python-icat, when trying to create a client we get an error from `getEntityInfo`: `icat.exception.ICATParameterError: Parameter is not an ICAT entity`. @ajkyffin has pointed out that python-icat queries for the entity info of the "Parameter" entity, which isn't a real entity in icat.server (see https://github.com/icatproject/python-icat/blob/develop/src/icat/entities.py#L253). The commit on icat.server which changed what is returned from `getEntityInfo` is here: https://github.com/icatproject/icat.server/commit/7420ced7ad3592e919efc87610d5790ab9c81462

Alan could modify icat.server to return entity info for "Parameter" to keep in line with old behaviour, but that seems like the wrong thing to do and instead we should not expect to have "Parameter" be valid for getting entity info

**Comment by RKrahl** [comment]
But then, this change in `icat.server` is a breaking change that should be discussed in the community and certainly not be made in a minor release.

**Comment by ajkyffin** [comment]
My intention was not to make any breaking changes so I'll add back the ability to get entity info for Parameter into icat.server.

**Comment by RKrahl** [comment]
I guess, we can discuss this in the collaboration meeting next week.

In the meanwhile, I mark this one with question tag, pending this discussion.

**Comment by RKrahl** [comment]
As discussed in the collaboration meeting this week, `icat.server` will for the time being continue to deliver entity info for the abstract class `Parameter`. There is thus no need to change python-icat in this point.
