### ISSUE TITLE
IDSClient.getData() throws HTTPError when requesting a large number of objects

### ISSUE THREAD

**Issue by RKrahl** [icatproject/python-icat#22]
IDSClient.getData() throws HTTPError when trying to download a large number of datafiles:
```python
>>> datafiles = client.search("SELECT df FROM Datafile df LIMIT 0,880")
>>> len(datafiles)
880
>>> client.getData(datafiles)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.3/site-packages/icat/client.py", line 853, in getData
    return self.ids.getData(objs, compressFlag, zipFlag, outname, offset)
  File "/usr/lib/python3.3/site-packages/icat/ids.py", line 375, in getData
    return self.default.open(req)
  File "/usr/lib64/python3.3/urllib/request.py", line 475, in open
    response = meth(req, response)
  File "/usr/lib64/python3.3/urllib/request.py", line 587, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.3/urllib/request.py", line 513, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.3/urllib/request.py", line 447, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.3/site-packages/icat/ids.py", line 69, in http_error_default
    raise err
urllib.error.HTTPError: HTTP Error 400: Bad Request
```
The error has been reproduced with Python 2.7, 3.3, and 3.5.

There is no trace of the call in the IDS server's log files.  It seems that the call fails even before it is sent to the server.

This issue was originally reported by Jianguo Rao by mail.

**Comment by RKrahl** [comment]
Note that the getData IDS call is a HTTP GET request.  The client needs to place the list of all datafile ids in the "datafileIds" parameter in the HTTP query.  With more then 800 datafiles, this makes a huge query string.  It seems that this hits some internal limit in the Python urllib library.  It may be that there is no reasonable way for python-icat to get such a large requests sent to the server.  However "HTTP Error 400: Bad Request" is very unspecific, a more meaningful error would be desirable.

Need to investigate more if there is a predictable limit on the number of objects or on the length of the query that will work with the Python standard library.

**Comment by RKrahl** [comment]
For an even larger number of objects, the Python standard library throws another error:
```python
>>> datafiles = client.search("SELECT df FROM Datafile df LIMIT 0,1000")
>>> len(datafiles)
1000
>>> client.getData(datafiles)
Traceback (most recent call last):
  ...
urllib.error.HTTPError: HTTP Error 414: Request-URI Too Long
```

Depending on the findings after digging in the guts of urllib, this may be worth a bug report against urllib.  (If it hits an internal limit, it should always raise a 414 rather then a 400.)

**Comment by fisherab** [comment]
Rolf,

To avoid this problem all my restful clients check the length of the
generated URL before making a call and then raise an exception if too long.
I limit it to 2048 which as far as I know all common clients and servers
can deal with.

Steve

**Comment by RKrahl** [comment]
Steve,

yes, apparently, the Python standard library (urllib) does similar checks.  This is not the problem, raising an error is justified for too large requests.  Only the unspecific error message is not very helpful and a more meaningful error would be desired.

I only need to investigate: what are the limits imposed by the standard lib?  Are they predictable?  What is the reason for the two different errors, "400: Bad Request" vs. "414: Request-URI Too Long"?  (Hence the "question" tag.)

Note by the way that there [don't seem to be any common limit for clients and servers](http://stackoverflow.com/questions/266322/http-uri-get-limit).

**Comment by RKrahl** [comment]
As mentioned above, there is no trace of the failed call in the IDS server's log files.  This made me believe that the request was not even sent to the server and that the limitation came from urllib.  This turned out to be wrong.  Apparently GlassFish throws an error if the overall request line exceeds 7967 characters.  The "414: Request-URI Too Long" error came from the Apache proxy having a somewhat larger limit.  Other containers may of course have different limits.

I will close as wontfix because if the limitation is not on the client side then there is no way for python-icat to reliably predict the limit.
