### ISSUE TITLE
Potential Issue ids.getServiceStatus()

### ISSUE THREAD

**Issue by solcaj** [icatproject/python-icat#29]
## Issue

Not sure about it, unfortunately I have no time to check the source code but perhaps there is an issue with 

```
ids.getServiceStatus()
```
## steps to reproduce : 
 
indeed assume `client.getUsername()`  returns _simple/root_ the current logged in user. 
But in the _ids.properties_ file one defines 

```
rootUserNames = root
``` 
And thus the potential clash when calling `client.ids.getServiceStatus()`..
```
{IDSInsufficientPrivilegesError}simple/root is not included in the ids rootUserNames set.
```

### current infrastructure for the test 
icat.server-4.6.1      <ejb, webservices, web>
ids.server-1.5.0       <ejb, webservices, web>
topcat-2.0.1-SNAPSHOT  <ejb, webservices, web>

**Comment by RKrahl** [comment]
Of course this may happen.  But it is not an error in python-icat, neither in ids.server.  It is rather a configuration error in your installation.

If your root user name according your authentication plugin is `simple/root`, then you must put this name in `rootUserNames`, both in icat.properties and in ids.properties.  If you don't, then your root user does not have root privileges and the IDSInsufficientPrivilegesError is correct.

In any case, this error is what the IDS server replied and so the client can only report this reply.

**Comment by solcaj** [comment]
you're right it makes sense but this is not my setup but rather the setup provided in the TopCAT Vagrant VM. I think it would be interesting for the future to not rely on configuration settings on whether the user includes or not the mechanism label in the _rootUserNames_ fields, since the mechanism labels must be set in order to use this prefixed root user names in the _properties_ files ..

**Comment by fisherab** [comment]
The Vagrant file in TopCAT is for the convenience of TopCAT developers and
is not meant for general use.

In general the mechanism needs to be specified in order to avoid ambiguity.
I would have liked to make the mechanism compulsory but have not made done
so to avoid backwards incompatibility.
