### ISSUE TITLE
Extend icatrestore to become a generic ingestion tool

### ISSUE THREAD

**Issue by RKrahl** [icatproject/python-icat#4]
Currently, icatrestore reads a dump file and creates all entity objects defined therein in the ICAT server.  This has been designed for the use case to restore the full content of an ICAT, where the dump file has previously been created by icatdump.  But it could in principle also be used as an ingestor, to add only a few objects to an ICAT that already has content.

But there are a few things in the dump file format that are somewhat impractical for the latter use case:
* icatrestore assumes that all the objects in the dump file are to be created in the ICAT.  It should also be possible to list objects that are assumed to already exist as a prerequisite in order to reference them by other objects to be created.
* relations between objects are expressed using the keys as returned by the getUniqueKey() call.  But creators of an ingest file will likely not be able to generate these keys.  It should also be possible to reference existing objects by attribute values.

**Comment by RKrahl** [comment]
This might get implemented for some file formats only.  E.g. in XML, we have the distinction between attributes and subelements of an element.  This may be used to distinguish between referencing an existing object by its attributes and creating a new one having attribute values as set in the subelements.  In YAML, it might be much more difficult to express this distinction.

**Comment by fisherab** [comment]
The import in the restful interface has this capability already as I understand your idea.

**Comment by RKrahl** [comment]
Yes, I guess that's true.  But for the import in the restful interface the user would have to provide the input in the proprietary ICAT import format.  icatrestore would accept XML as input which may be easier to produce with existing tools and libraries.

**Comment by fisherab** [comment]
I think it would be preferable to extend the ICAT import/export facility to support other formats. YAML should be easy. XML should also be easy if there is a real need for it - however I don't like its verbosity. JSON might be provided for "completeness". The benefit of having the code in the server is that all clients can use it.

**Comment by RKrahl** [comment]
Of course, there s nothing to be said against extending the ICAT import/export facility to support other formats.  But I don't think that we must decide whether file import/export is do be done either on the client side or on the server side.  We can have both and I think both have their use.  Furthermore, as far as this issue is concerned, as pointed out above, it's already almost there.  The icatrestore/icatdump in the current python-icat version is already able to do this.  It only needs a few small modifications to improve the ease of use for this particular use case.  Since I currently need this feature here at HZB, I think I'm going to do this further step at the client side.

If you intend to support more file file formats for the import/export facility on the server side, I think we should try to agree on common file formats.  You might want to have a look on the files that  icatrestore/icatdump currently consumes and generates.  Concerning XML, you're right about its verbosity.  But right this verbosity also have its own advantages: it makes some things easier to express for the generator of the file.  Furthermore there is a big support with libraries for XML.  That is why I will probably use XML for the data ingest.
