### ISSUE TITLE
API calls should take session ID as a parameter

### ISSUE THREAD

**Issue by gc-code** [icatproject/python-icat#55]
I have recently been working on a web service that uses python-icat. The service takes the user's ICAT session ID to ensure they have the correct permissions according to the ICAT rules. In order to achieve this in Python ICAT I have to reset the session ID each time I make a call like so:

```
client.sessionId = user_session
results = client.search("....")
client.sessionId = None
```

This isn't thread safe and clutters the code. It would be useful to have a set of methods in python-icat that would allow a session ID to be supplied in a thread safe way.

I will be modifying the code to use the ICAT REST API directly, unless there is something I have overlooked.

**Comment by RKrahl** [comment]
Concerning thread-safety, please note that the underlying package Suds is not thread safe. So each thread must have its own separate `Client` instance anyway. (And then, thread-safety is not an issue any more.)

I use python-icat in web service scripts (based on Flask) and my scripts typically look like:
```python
from flask import Flask
import icat
import icat.config

icat.config.defaultsection = "ingest"

# [...]

def get_icat_client():
    client, conf = icat.config.Config(ids=False).getconfig()
    client.login(conf.auth, conf.credentials)
    return client

# [...]

@app.route('/', methods=['POST'])
def some_call():
    client = get_icat_client()
    # [...]
```

These are scripts that login to ICAT as a privileged user, but you see the principle: each thread creates its own client instance in thread local memory. There is a configuration file with a section "ingest" in this case. If you want to use the session from the user, you may do something like:

```python
from flask import Flask
import icat
import icat.config

icat.config.defaultsection = "user"

# [...]

def get_icat_client(sessionId):
    client, conf = icat.config.Config(ids=False).getconfig()
    ciient.sessionId = sessionId
    client.autoLogout = False
    return client

# [...]

@app.route('/', methods=['POST'])
def some_call():
    user_session = ...
    client = get_icat_client(user_session)
    # [...]
```

**Comment by RKrahl** [comment]
And by the way: if you intend to modify the code to use the ICAT REST API, why would you want to use python-icat in the first place? python-icat is based on the SOAP API. Changing it to use REST would more or less mean to rewrite the whole thing. There wont be much left from python-icat then. That is why I never bothered to support the REST API, because that would be an entirely new project from scratch.

**Comment by gc-code** [comment]
It is still cumbersome to reset a state variable every time a different session is being used. Seeing as the underlying SOAP call takes a session ID, shouldn't Python ICAT seek to mimic that?

I haven't written a large amount of code on the project, so it wouldn't be too difficult to convert it to using the REST API.

**Comment by gc-code** [comment]
I've modified my code based on your suggestion above, it works well. As you say, the separate client objects make it thread safe and also avoid the need to reset the session ID every time. Thanks, this issue can now be closed.

**Comment by RKrahl** [comment]
Glad to hear that it works for you.
