### ISSUE TITLE
Consider to switch to suds-community

### ISSUE THREAD

**Issue by RKrahl** [icatproject/python-icat#67]
The original version of `suds` is dead since very long time.  Jurko Gospodnetić has been taken over and created the `suds-jurko` fork. But development seem to have stalled again since 2015. Many new forks have been created since then, most of them rather short-lived. Now, there is one that lasted a little bit longer and at least has recent activity: [suds-community](https://pypi.org/project/suds-community/).

Should test the latter and evaluate whether it works with python-icat. If positive, update documentation to point to that one as system requirement in the README.

**Comment by louise-davies** [comment]
Hi Rolf, I've actually been using `python-icat` with `suds-community` since starting some work a few days ago. I haven't comprehensively tested it but it has been working fine for me so far.

**Comment by RKrahl** [comment]
Thanks for the feedback! Good to hear that it works.

**Comment by RKrahl** [comment]
Further testing reveals that `suds-community` does not work for ICAT older the 4.9.0, see #72.
