### ISSUE TITLE
Allow Query.setAttribute() to set a list of attribute names

### ISSUE THREAD

**Issue by MRichards99** [icatproject/python-icat#76]
Currently, the `setAttribute()` function in the Query object accepts a single attribute name. This feature works well, but it would be great to expand this function to accept a list of attribute names.

On the DataGateway API I'm working on for STFC, the API uses a distinct field filter to get a distinct list of results of the fields requested in the filter. A filter containing `["name", "title"]` would return a distinct list of results of the following format:

```json
[
    {
        "name": "Name of investigation",
        "title": "Investigation title"
    },
    {
        "name": "Second investigation",
        "title": "Title of investigation"
    }
]
```

This could be achieved by expanding `setAttribute()` as described above and adding a DISTINCT aggregate to the query. This would be a better alternative to my current solution for the API which isn't robust enough.

Hopefully this could be implemented into Python ICAT as it's something that should work if I was directly sending a query to `icatdb` :)

**Comment by RKrahl** [comment]
Hi @MRichards99, thanks for that feedback!

Unfortunately, it's not that easy, there is more then one level of processing of the query to consider.

First of all, the `icat.query.Query` class is just a helper to build query strings. So if it were only the `Query` class missing the feature, you could always bypass it and create the query strings yourself. So, instead of
```python
>>> query = Query(client, "Investigation", attribute="name")
>>> result = client.search(query)
```
you can always write
```python
>>> query = "SELECT o.name FROM Investigation o"
>>> result = client.search(query)
```
In fact, there are use cases where you have to, because the `Query` class does not support the full complexity of JPQL queries.

Now, if you try the following, you'll notice a very strange error message:
```python
>>> query = "SELECT o.name, o.title FROM Investigation o"
>>> result = client.search(query)
ERROR:suds.client:<suds.sax.document.Document object at 0x7f65b8d61cf8>
Traceback (most recent call last):
  ...
xml.parsers.expat.ExpatError: no element found: line 4, column 177

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  ...
xml.sax._exceptions.SAXParseException: <unknown>:4:177: no element found
```
(Actually, I'm rather surprised to see it after trying myself, I was expecting to get an `ICATParameterError` instead. So there is also another issue in the error handling that I might need to look into.)

Beside the strange error message, the real problem is that `icat.server` features two different flavours of JPQL queries: one that is exposed at the "RESTful" interface and one exposed at the SOAP interface. Since python-icat is a client for the SOAP interface, it can only offer the JPQL query syntax available there. The syntax of the SOAP flavour is somewhat reduced, it does for instance not support multiple attributes in the query.

So, I'm afraid, this is a missing feature in `icat.server` and there is little that python-icat could do here.

**Comment by MRichards99** [comment]
Hi @RKrahl

I've been using 0.18.0 (and 4.11.1 of ICAT Server) to implement these changes onto DataGateway API. Multiple attributes can be selected without issue so that's good! However, our use case requires selecting multiple attributes with the DISTINCT keyword, something that gives an `ICATParameterError`. Something like the following:

```python
from icat.client import Client
from icat.query import Query

icat_url = "https://localhost.localdomain:8181"

client = Client(icat_url, checkCert=False)
client.login("simple", {"username": "root", "password": "pw"})

my_query = Query(client, "User", aggregate="DISTINCT", attributes=["fullName", "email"])
results = client.search(my_query)
```

Exception received:
```
icat.exception.ICATParameterError: An exception occurred while creating a query in EntityManager: 
Exception Description: Syntax error parsing [SELECT DISTINCT ( o.fullName , o.email ) FROM User o]. 
[16, 37] The select expression is not a valid expression.
```

I experimented with the JPQL query on `/entityManager` to see if I could get something working. I found that removing the brackets around the distinct attributes worked (i.e. `SELECT DISTINCT o.fullName , o.email FROM User o`). However, I can fully understand the brackets are essential when multiple aggregate keywords are used in a single query. `SELECT COUNT ( DISTINCT ( o.email , o.fullName ) ) FROM User o` would be an example of this, which is also a potential use case for our API.

Do you know if this could be fixed at all? Thanks!

**Comment by RKrahl** [comment]
Hi @MRichards99,

as already pointed out in a comment above, the `Query` class is just a tool that helps you to build query strings. You can always bypass it and create the query strings your own.  Trying that, it confirms your observation that `DISTINCT` without brackets works (also at the SOAP interface):
```python
>>> client.search("SELECT DISTINCT o.fullName, o.email FROM User o")
[[Aelius Cordus, acord@example.org], [Arnold Hau, ahau@example.org], [Jean-Baptiste Botul, jbotu@example.org], [John Doe, jdoe@example.org], [Nicolas Bourbaki, nbour@example.org], [Rudolph Beck-Dülmen, rbeck@example.org], [IDS reader], [Root], [User Office]]
>>> client.search("SELECT o.fullName, o.email FROM User o")
[[Aelius Cordus, acord@example.org], [Arnold Hau, ahau@example.org], [Jean-Baptiste Botul, jbotu@example.org], [John Doe, jdoe@example.org], [Nicolas Bourbaki, nbour@example.org], [Rudolph Beck-Dülmen, rbeck@example.org], [IDS reader], [Root], [User Office], [Aelius Cordus, acord@example.org]]
```

As you can see from this test, I created an extra user having the same `fullName` and `email` as an already existing one to test that `DISTINCT` has the expected effect on the result:

```python
>>> len(client.search("SELECT DISTINCT o.fullName, o.email FROM User o"))
9
>>> len(client.search("SELECT o.fullName, o.email FROM User o"))
10
>>> len(client.search("SELECT DISTINCT o.name, o.fullName, o.email FROM User o"))
10
>>> len(client.search("SELECT o.name, o.fullName, o.email FROM User o"))
10
```

So this might already help you to work around the issue.

I found no way to get `COUNT:DISTINCT` to work, regardless how I tried to add and omit brackets at different places. Also `COUNT` alone does not work with multiple attributes, with or without brackets.

In fact, I did notice already during testing before the release of 0.18.0 that `DISTINCT` with multiple attributes does not work. But I never tried to omit the brackets, so I assumed this to be a limitation in icat.server that I would not be able to fix on the client side.

Now I wonder if I should take this special case into account in the `Query` class. For my feeling, the query with an aggregate without brackets looks just odd. As you already noted yourself it would break for multiple aggregate functions, even for a single attribute which currently works. So it would need to be a condition like: "if there are multiple attributes, omit the brackets for the aggregate, but only if that aggregate is `DISTINCT` alone". Sounds like an odd condition …

**Comment by RKrahl** [comment]
Ok, I decided to fix that shortly.
