### ISSUE TITLE
Ordering on One to Many Relationships

### ISSUE THREAD

**Issue by MRichards99** [icatproject/python-icat#83]
On DataGateway, there's a use case where we'd like to sort results on a field which has a one to many relationship. An example can be seen below:

```python
test_query = Query(client, "Investigation", order=("investigationInstruments.instrument.fullName", "ASC"))
```

This query results in a `ValueError`, which is thrown on [L283 of query.py](https://github.com/icatproject/python-icat/blob/develop/icat/query.py#L283). I removed this exception on my local version of Python ICAT (and rearranged the conditionals around it so it would work) and the query was successful. A couple of warnings were printed in my terminal but the JPQL itself appeared to behave as expected.

I've been given a JPQL query that's used in TopCAT which also orders on this field:
```sql
select distinct investigation from Investigation investigation , investigation.investigationInstruments as investigationInstrumentPivot , investigationInstrumentPivot.instrument as investigationInstrument
where investigation.id BETWEEN 86387810 AND 86388810
order by investigationInstrument.fullName desc , investigation.id asc
limit 0, 50
include investigation.investigationInstruments.instrument
```

I believe ISIS only have a single instrument per investigation so we display each one alongside its associated investigation in DataGateway's table view. We're unsure of the HZB use case (for example if you have multiple instruments per investigation?) which might've resulted in the exception implemented in Python ICAT. 

We're interested on your thoughts regarding this and how we might be able to sort on fields with a one to many relationship for our use case. 

Thanks!

**Comment by RKrahl** [comment]
Dear @MRichards99, as far as I remember, I disabled one to many relationships in `ORDER BY` clauses because I found that ICAT does not support this. If you now tell me that this kind of query did work in your case, this is surprising news. In any case, that is not trivial, because there are different cases to consider, depending on the number of related objects for this relation (zero, one, many). I have to look into that.

**Comment by MRichards99** [comment]
Were there any specific cases you found where this behaviour wasn't supported?

Here's another use case I've found in TopCAT, functionality we'd like to recreate in DataGateway:

```sql
select distinct investigation from Investigation investigation , investigation.facility as facility , facility.instruments as instrument , facility.facilityCycles as facilityCycle , investigation.investigationInstruments as investigationInstrumentPivot , investigationInstrumentPivot.instrument as investigationInstrument , investigation.studyInvestigations as studyInvestigationPivot , studyInvestigationPivot.study as study
where facility.id = 1 and instrument.id = 28 and facilityCycle.id = 87730657 and investigationInstrument.id = instrument.id and investigation.startDate BETWEEN facilityCycle.startDate AND facilityCycle.endDate
ORDER BY study.pid asc , investigation.id asc limit 0, 50
include investigation.studyInvestigations.study, investigation.investigationInstruments.instrument
```

When we show a table of investigations, we also display `study.pid` in the table and since the table columns are sortable, we'd like to be able to sort on this field from the investigation entity. Here's a screenshot (taken from DataGateway) to demonstrate this point:
![image](https://user-images.githubusercontent.com/32678030/122212736-18bc1280-cea0-11eb-8710-156c95b3fd94.png)

**Comment by RKrahl** [comment]
@MRichards99, to be honest I'm not able to recall the exact reason why I put that condition in the code (it was six years ago). As you point out, ordering by a one to many relationship works (in principle) and also did work back then.

There is however caveats, the search may have surprising results: if you have multiple related objects for that relation, the search will yield duplicates in the result list. It will contain as many copies of the same object as there are distinct values in the tuple given by the `ORDER BY` clause. Even the `DISTINCT` modifier does not change that behavior.

Example:
```
>>> client.search("SELECT DISTINCT inv FROM Investigation inv")
[(investigation){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:55+02:00
   id = 31
   modId = "simple/root"
   modTime = 2021-06-29 18:13:55+02:00
   doi = "00.0815/inv-00122"
   name = "08100122-EF"
   startDate = 2008-03-13 11:39:42+01:00
   title = "Durol single crystal"
   visitId = "1.1-P"
 }, (investigation){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:56+02:00
   id = 32
   modId = "simple/root"
   modTime = 2021-06-29 18:13:56+02:00
   doi = "00.0815/inv-00601"
   endDate = 2010-10-12 17:00:00+02:00
   name = "10100601-ST"
   startDate = 2010-09-30 12:27:24+02:00
   title = "Ni-Mn-Ga flat cone"
   visitId = "1.1-N"
 }, (investigation){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:56+02:00
   id = 33
   modId = "simple/root"
   modTime = 2021-06-29 18:13:56+02:00
   doi = "00.0815/inv-00409"
   endDate = 2012-08-06 03:10:08+02:00
   name = "12100409-ST"
   startDate = 2012-07-26 17:44:24+02:00
   title = "NiO SC OF1 JUH HHL"
   visitId = "1.1-P"
 }]
>>> client.search("SELECT DISTINCT inv FROM Investigation inv, inv.investigationUsers as iu ORDER BY iu.role")
[(investigation){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:55+02:00
   id = 31
   modId = "simple/root"
   modTime = 2021-06-29 18:13:55+02:00
   doi = "00.0815/inv-00122"
   name = "08100122-EF"
   startDate = 2008-03-13 11:39:42+01:00
   title = "Durol single crystal"
   visitId = "1.1-P"
 }, (investigation){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:56+02:00
   id = 33
   modId = "simple/root"
   modTime = 2021-06-29 18:13:56+02:00
   doi = "00.0815/inv-00409"
   endDate = 2012-08-06 03:10:08+02:00
   name = "12100409-ST"
   startDate = 2012-07-26 17:44:24+02:00
   title = "NiO SC OF1 JUH HHL"
   visitId = "1.1-P"
 }, (investigation){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:56+02:00
   id = 32
   modId = "simple/root"
   modTime = 2021-06-29 18:13:56+02:00
   doi = "00.0815/inv-00601"
   endDate = 2010-10-12 17:00:00+02:00
   name = "10100601-ST"
   startDate = 2010-09-30 12:27:24+02:00
   title = "Ni-Mn-Ga flat cone"
   visitId = "1.1-N"
 }, (investigation){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:55+02:00
   id = 31
   modId = "simple/root"
   modTime = 2021-06-29 18:13:55+02:00
   doi = "00.0815/inv-00122"
   name = "08100122-EF"
   startDate = 2008-03-13 11:39:42+01:00
   title = "Durol single crystal"
   visitId = "1.1-P"
 }]
```
Note that investigation "08100122-EF" appears twice in the second search result. This investigation has three `investigationUsers`, having two distinct values in the `role` attribute.

You also may have objects missing from the result.  Example:
```
>>> client.search("SELECT DISTINCT s FROM Sample s")
[(sample){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:55+02:00
   id = 31
   modId = "simple/root"
   modTime = 2021-06-29 18:13:55+02:00
   name = "Durol SC"
   pid = "ESNFHNS8AYEZ"
 }, (sample){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:56+02:00
   id = 32
   modId = "simple/root"
   modTime = 2021-06-29 18:13:56+02:00
   name = "NiMnGa 991027"
   pid = "ESNFZDVHICBD"
 }, (sample){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:56+02:00
   id = 33
   modId = "simple/root"
   modTime = 2021-06-29 18:13:56+02:00
   name = "Nickel(II) oxide SC"
   pid = "ESNFX8C7B53W"
 }]
>>> client.search("SELECT DISTINCT s FROM Sample s JOIN s.parameters AS sp ORDER BY sp.stringValue")
[(sample){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:56+02:00
   id = 32
   modId = "simple/root"
   modTime = 2021-06-29 18:13:56+02:00
   name = "NiMnGa 991027"
   pid = "ESNFZDVHICBD"
 }, (sample){
   createId = "simple/root"
   createTime = 2021-06-29 18:13:56+02:00
   id = 33
   modId = "simple/root"
   modTime = 2021-06-29 18:13:56+02:00
   name = "Nickel(II) oxide SC"
   pid = "ESNFX8C7B53W"
 }]
```
Note that "Durol SC" is missing from the second search, because it has no parameter. In the case of a nullable many to one relation, the `Query` class emits a warning for that reason.

Anyway, python-icat is not the censor of ICAT features. If a query works in principle (and can be generated with reasonable effort), it should be supported by the `Query` class, regardless whether the results are sensible. So I'll remove that condition.

**Comment by RKrahl** [comment]
… addition: I do however consider to emit a warning, something like “ordering on a one to many relation may surprisingly affect the search result”. What do you think about this?
