### ISSUE TITLE
Add OR Functionality to Conditions

### ISSUE THREAD

**Issue by MRichards99** [icatproject/python-icat#93]
As I'm sure you're aware, the ExPANDS search API requires the `and` and `or` keywords to be supported for the [API's WHERE query filter](https://github.com/panosc-eu/search-api/blob/master/doc/query.md#joining-queries). Python ICAT supports AND already, but does not support OR. For our implementation of the search API, we would need this functionality to be added to Python ICAT.

I'm just opening this issue for awareness :)

**Comment by RKrahl** [comment]
We wont implement this for the time being.
